import React, { useState, useEffect } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import { GitCommit, ArrowRight, ShieldAlert, Cpu, Activity, Database, Key, Server, Lock } from 'lucide-react';

export default function AIInvestigation() {
  const [searchParams] = useSearchParams();
  const selectedIncId = searchParams.get('incidentId') || 'INC-1001';
  const [incidentId, setIncidentId] = useState(selectedIncId);
  const [sequence, setSequence] = useState([]);
  const [loading, setLoading] = useState(false);
  const { showToast, systemMode } = useAuth();
  const navigate = useNavigate();

  const runInvestigation = async (incId) => {
    setLoading(true);
    showToast(`Correlating security logs for ${incId}...`, 'account_tree');
    try {
      const res = await api.post(`/incidents/${incId}/investigate`);
      if (res.data.attackSequence) {
        setSequence(res.data.attackSequence);
      }
    } catch (err) {
      console.warn('Investigation fallback');
      setSequence([
        { step: 1, stage: 'Reconnaissance', description: `24 failed SSH logins from 45.33.22.11 targeting root account`, timestamp: 'T+00:00:00' },
        { step: 2, stage: 'Authentication Probe', description: 'Successful SSH authentication established for user root', timestamp: 'T+00:01:15' },
        { step: 3, stage: 'Privilege Escalation', description: 'Interactive sudo subshell elevated without MFA challenge', timestamp: 'T+00:02:30' },
        { step: 4, stage: 'Sensitive Access', description: 'LSASS memory dump process executed in staging directory', timestamp: 'T+00:03:10' },
        { step: 5, stage: 'Data Exfiltration', description: '580MB outbound POST request initiated to external cloud bucket', timestamp: 'T+00:04:45' }
      ]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    runInvestigation(incidentId);
  }, [incidentId]);

  return (
    <div className="w-full px-6 py-6 flex flex-col gap-6">
      {/* Header Banner */}
      <div className="bg-surface-container-lowest border border-outline-variant/60 rounded-xl p-6 shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-primary text-on-primary flex items-center justify-center shadow-md">
            <GitCommit className="w-7 h-7" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="font-headline-lg text-headline-lg font-bold text-on-surface">AI Incident Investigation & Correlation</h1>
              <span className="text-xs bg-surface-container text-primary font-bold px-3 py-1 rounded-full border border-primary/20">
                Event Graph Reconstructor
              </span>
            </div>
            <p className="font-body-sm text-sm text-outline mt-0.5">
              Correlates multiple security events to reconstruct probable attack sequences and identify root-cause relationships.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <select
            value={incidentId}
            onChange={(e) => {
              setIncidentId(e.target.value);
              runInvestigation(e.target.value);
            }}
            className="bg-surface-container-low border border-outline-variant/40 rounded-xl px-4 py-2.5 text-xs font-bold text-on-surface outline-none cursor-pointer"
          >
            <option value="INC-1001">INC-1001 (Brute Force Attack)</option>
            <option value="INC-1002">INC-1002 (Port Scanning)</option>
            <option value="INC-1003">INC-1003 (Privilege Escalation)</option>
            <option value="INC-1004">INC-1004 (Unusual Data Transfer)</option>
            <option value="INC-1005">INC-1005 (False Positive Login Alert)</option>
          </select>
        </div>
      </div>

      {/* Visual Attack Correlation Flow Diagram */}
      <div className="bg-surface-container-lowest border border-outline-variant/60 rounded-xl p-6 shadow-sm flex flex-col gap-6">
        <div className="flex items-center justify-between border-b border-outline-variant/40 pb-4">
          <div>
            <h2 className="font-headline-sm text-headline-sm font-bold text-on-surface">
              Correlated Attack Path: {incidentId}
            </h2>
            <span className="text-xs text-outline">Sequential causality graph generated by Python AI service</span>
          </div>

          <span className="text-xs font-bold text-emerald-600 border border-emerald-300 px-3 py-1 rounded-full bg-emerald-50">
            {systemMode}
          </span>
        </div>

        {/* Visual Node Flow */}
        <div className="flex flex-col lg:flex-row items-center justify-between gap-4 py-6 px-4 bg-surface-container-low rounded-xl border border-outline-variant/30 overflow-x-auto">
          {sequence.map((step, idx) => (
            <React.Fragment key={idx}>
              <div className="flex flex-col items-center text-center p-4 bg-surface-container-lowest rounded-xl border border-outline-variant/50 shadow-sm min-w-[180px] max-w-[200px] card-hover-lift">
                <div className="w-10 h-10 rounded-full bg-primary/10 text-primary flex items-center justify-center font-bold text-sm mb-2">
                  {step.step || idx+1}
                </div>
                <span className="font-label-sm text-xs font-bold text-on-surface">{step.stage || 'Stage'}</span>
                <p className="text-[11px] text-outline mt-1 line-clamp-2">{step.description}</p>
                <span className="text-[10px] font-mono text-primary font-bold mt-2">{step.timestamp}</span>
              </div>

              {idx < sequence.length - 1 && (
                <div className="hidden lg:flex items-center text-outline">
                  <ArrowRight className="w-6 h-6 animate-pulse" />
                </div>
              )}
            </React.Fragment>
          ))}
        </div>

        {/* Detailed Timeline Events */}
        <div className="flex flex-col gap-3 mt-2">
          <h3 className="font-headline-sm text-sm font-bold text-on-surface">Step-by-Step Chronological Findings</h3>
          {sequence.map((step, idx) => (
            <div key={idx} className="flex items-start gap-4 p-4 rounded-xl bg-surface-container-low border border-outline-variant/40 text-xs">
              <div className="w-7 h-7 rounded-lg bg-primary text-on-primary font-bold flex items-center justify-center shrink-0">
                {step.step || idx+1}
              </div>
              <div className="flex flex-col gap-1">
                <div className="flex items-center gap-3">
                  <strong className="font-bold text-on-surface text-xs">{step.stage}</strong>
                  <span className="font-mono text-outline text-[11px]">{step.timestamp}</span>
                </div>
                <p className="text-on-surface-variant leading-relaxed">{step.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
