import React, { useState, useEffect } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import { GitCommit, ArrowRight, ShieldAlert, Cpu, Activity, Database, Key, Server, Lock } from 'lucide-react';

export default function AIInvestigation() {
  const [searchParams] = useSearchParams();
  const selectedIncId = searchParams.get('incidentId') || 'INC-1001';
  const [incidentId, setIncidentId] = useState(selectedIncId);
  const [sequence, setSequence] = useState([]);
  const [loading, setLoading] = useState(false);
  const { showToast, systemMode } = useAuth();
  const navigate = useNavigate();

  const runInvestigation = async (incId) => {
    setLoading(true);
    showToast(`Correlating security logs for ${incId}...`, 'account_tree');
    try {
      const res = await api.post(`/incidents/${incId}/investigate`);
      if (res.data.attackSequence) {
        setSequence(res.data.attackSequence);
      }
    } catch (err) {
      console.warn('Investigation fallback');
      setSequence([
        { step: 1, stage: 'Reconnaissance', description: `24 failed SSH logins from 45.33.22.11 targeting root account`, timestamp: 'T+00:00:00' },
        { step: 2, stage: 'Authentication Probe', description: 'Successful SSH authentication established for user root', timestamp: 'T+00:01:15' },
        { step: 3, stage: 'Privilege Escalation', description: 'Interactive sudo subshell elevated without MFA challenge', timestamp: 'T+00:02:30' },
        { step: 4, stage: 'Sensitive Access', description: 'LSASS memory dump process executed in staging directory', timestamp: 'T+00:03:10' },
        { step: 5, stage: 'Data Exfiltration', description: '580MB outbound POST request initiated to external cloud bucket', timestamp: 'T+00:04:45' }
      ]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    runInvestigation(incidentId);
  }, [incidentId]);

  return (
    <div className="w-full space-y-6">
      {/* Header Banner */}
      <div className="bg-white border border-[#E8ECF0] rounded-xl p-5 shadow-[0_2px_8px_rgba(15,23,42,0.03)] flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-[#07111F] text-white flex items-center justify-center shadow-xs">
            <GitCommit className="w-5 h-5 text-blue-400" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-xl font-bold text-[#07111F] tracking-tight">Attack Sequence & Correlation Graph</h1>
              <span className="text-xs font-mono font-semibold bg-[#ECFDF3] text-[#027A48] px-2.5 py-0.5 rounded border border-[#ABE5C6]">
                ● SYSTEM ONLINE | SIMULATION MODE
              </span>
            </div>
            <p className="text-xs text-[#667085] mt-0.5">
              Correlates multi-stage security events to reconstruct sequential causal attack graphs and root causes.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <select
            value={incidentId}
            onChange={(e) => {
              setIncidentId(e.target.value);
              runInvestigation(e.target.value);
            }}
            className="bg-[#FAFBFC] border border-[#E2E8F0] rounded-lg px-3 py-2 text-xs font-semibold text-[#07111F] outline-none cursor-pointer"
          >
            <option value="INC-1001">INC-1001 (Brute Force Attack)</option>
            <option value="INC-1002">INC-1002 (Port Scanning)</option>
            <option value="INC-1003">INC-1003 (Privilege Escalation)</option>
            <option value="INC-1004">INC-1004 (Unusual Data Transfer)</option>
            <option value="INC-1005">INC-1005 (False Positive Login Alert)</option>
          </select>
        </div>
      </div>

      {/* Visual Attack Correlation Flow Diagram */}
      <div className="bg-white border border-[#E8ECF0] rounded-xl p-5 shadow-[0_4px_20px_rgba(15,23,42,0.04)] flex flex-col gap-6">
        <div className="flex items-center justify-between border-b border-[#E8ECF0] pb-3">
          <div>
            <h2 className="text-sm font-bold text-[#07111F]">
              Correlated Attack Path: {incidentId}
            </h2>
            <span className="text-xs text-[#667085]">Sequential causality graph generated by Python AI service</span>
          </div>

          <span className="text-xs font-mono font-semibold text-[#027A48] border border-[#ABE5C6] px-2.5 py-1 rounded bg-[#ECFDF3]">
            {systemMode}
          </span>
        </div>

        {/* Visual Node Flow */}
        <div className="flex flex-col lg:flex-row items-center justify-between gap-3 py-5 px-4 bg-[#FAFBFC] rounded-xl border border-[#E2E8F0] overflow-x-auto">
          {sequence.map((step, idx) => (
            <React.Fragment key={idx}>
              <div className="flex flex-col items-center text-center p-3.5 bg-white rounded-xl border border-[#E8ECF0] shadow-xs min-w-[170px] max-w-[190px]">
                <div className="w-8 h-8 rounded-full bg-[#EFF8FF] text-[#1570EF] border border-[#B2DDFF] flex items-center justify-center font-bold text-xs mb-2">
                  {step.step || idx+1}
                </div>
                <span className="text-xs font-bold text-[#07111F]">{step.stage || 'Stage'}</span>
                <p className="text-[11px] text-[#667085] mt-1 line-clamp-2">{step.description}</p>
                <span className="text-[10px] font-mono text-[#1570EF] font-semibold mt-2">{step.timestamp}</span>
              </div>

              {idx < sequence.length - 1 && (
                <div className="hidden lg:flex items-center text-[#94A3B8]">
                  <ArrowRight className="w-5 h-5" />
                </div>
              )}
            </React.Fragment>
          ))}
        </div>

        {/* Detailed Timeline Events */}
        <div className="flex flex-col gap-2.5 mt-1">
          <h3 className="text-xs font-bold text-[#07111F] uppercase font-mono tracking-wider">Step-by-Step Chronological Findings</h3>
          {sequence.map((step, idx) => (
            <div key={idx} className="flex items-start gap-3 p-3.5 rounded-lg bg-[#FAFBFC] border border-[#E8ECF0] text-xs">
              <div className="w-6 h-6 rounded bg-[#07111F] text-white font-mono text-xs font-bold flex items-center justify-center shrink-0">
                {step.step || idx+1}
              </div>
              <div className="flex flex-col gap-0.5">
                <div className="flex items-center gap-2">
                  <strong className="font-semibold text-[#07111F] text-xs">{step.stage}</strong>
                  <span className="font-mono text-[#667085] text-[11px]">{step.timestamp}</span>
                </div>
                <p className="text-[#344054] leading-relaxed">{step.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
